name: Build & Release

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.2.3

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.os.container }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            artifact_name: apt-remote.deb
          - os: macos-latest
            artifact_name: apt-remote.pkg
          - os: windows-latest
            artifact_name: apt-remote.msi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Linux & macOS need OpenSSL dev libs for reqwest
      - name: Install OpenSSL (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libssl-dev

      - name: Install OpenSSL (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install pkg-config openssl

      # Linux: install cargo-deb
      - name: Install cargo-deb
        if: matrix.os == 'ubuntu-22.04'
        run: cargo install cargo-deb

      # Windows: install WiX Toolset
      - name: Install WiX Toolset
        if: matrix.os == 'windows-latest'
        run: choco install wixtoolset --no-progress

      # Build step
      - name: Build Release
        run: cargo build --release

      # Package for Linux
      - name: Package as .deb
        if: matrix.os == 'ubuntu-22.04'
        run: cargo deb --no-build --output ${{ matrix.artifact_name }}

      # Package for macOS (.pkg)
      - name: Package as .pkg
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p pkgroot/usr/local/bin
          cp target/release/apt-remote pkgroot/usr/local/bin/
          pkgbuild --root pkgroot \
                   --identifier com.bhc1010.apt-remote \
                   --version ${GITHUB_REF_NAME#v} \
                   --install-location /usr/local/bin \
                   ${{ matrix.artifact_name }}

      # Package for Windows (.msi)
      - name: Package as .msi
        if: matrix.os == 'windows-latest'
        run: |
          candle installer.wxs
          light installer.wixobj -o ${{ matrix.artifact_name }}

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
